#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : horovod
Version  : 0.15.2
Release  : 4
URL      : https://github.com/uber/horovod/archive/v0.15.2.tar.gz
Source0  : https://github.com/uber/horovod/archive/v0.15.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: horovod-license = %{version}-%{release}
Requires: horovod-python = %{version}-%{release}
Requires: horovod-python3 = %{version}-%{release}
Requires: cffi
Requires: openmpi
BuildRequires : buildreq-distutils3
BuildRequires : cffi
BuildRequires : openmpi
BuildRequires : openmpi-dev
BuildRequires : tensorflow

%description
# Horovod
[![Build Status](https://travis-ci.org/uber/horovod.svg?branch=master)](https://travis-ci.org/uber/horovod) [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](LICENSE) [![FOSSA Status](https://app.fossa.io/api/projects/git%2Bgithub.com%2Fuber%2Fhorovod.svg?type=shield)](https://app.fossa.io/projects/git%2Bgithub.com%2Fuber%2Fhorovod?ref=badge_shield) [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/2373/badge)](https://bestpractices.coreinfrastructure.org/projects/2373)

%package license
Summary: license components for the horovod package.
Group: Default

%description license
license components for the horovod package.


%package python
Summary: python components for the horovod package.
Group: Default
Requires: horovod-python3 = %{version}-%{release}

%description python
python components for the horovod package.


%package python3
Summary: python3 components for the horovod package.
Group: Default
Requires: python3-core

%description python3
python3 components for the horovod package.


%prep
%setup -q -n horovod-0.15.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545258790
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/horovod
cp LICENSE %{buildroot}/usr/share/package-licenses/horovod/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/horovod/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
